<?php
/**
 * NeoTheme Austrlia (Neo Industries Pty Ltd)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Neo Industries Pty LTD Non-Distributable Software Modification License (NDSML)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.neotheme.com.au/legal/licenses/NDSM.html
 * If the license is not included with the package or for any other reason,
 * you did not receive your licence please send an email to
 * license@neotheme.com.au so we can send you a copy immediately.
 *
 * This software comes with no warrenty of any kind. By Using this software, the user agrees to hold
 * Neo Industries Pty Ltd harmless of any damage it may cause.
 *
 * @category    modules
 * @module      NeoTheme_ImageRotator
 * @copyright   Copyright (c) 2011 Neo Industries Pty Ltd (http://www.neotheme.com.au)
 * @license     http://www.neotheme.com.au/  Non-Distributable Software Modification License(NDSML 1.0)
 */
/**
 * @see NeoTheme_Blog_Block_Post_List
 */
?>
<?php //if ($this->getCategoryId()):?>
    <!--<div class="page-title">-->
    <!--    <h1>--><?php //echo $this->getCategory()->getName();?><!--</h1>-->
    <!--</div>-->
<?php //endif; ?>
<?php if (!$this->getCollection()->count()): ?>
    <div class="note-msg"><?php echo Mage::helper('neotheme_blog')->__('There are no posts in this category'); ?></div>
<?php else: ?>
    <?php $category = Mage::registry('current_blog_category'); ?>
    <?php if ($category->getViewType() == 0): ?>
        <?php $i = 1;
        foreach ($this->getCollection() as $post): ?>
            <div class="blog blog-summary fieldset" style="<?php if ($i == 1) {
                echo "margin: 0;";
            } ?>">
                <?php //maybe a better way of doing this maybe a getChildHtml('summary_');

                echo $this->getSummaryBlock($post)->toHtml();
                ?>
            </div>
            <?php $i++; endforeach; ?>
        <div class="toolbar"><?php echo $this->getPagerHtml(); ?></div>
    <?php else: ?>
        <div class="std">
            <div class="fp" id="fp">
                <div id="slider">
                    <div id="main-slider">
                        <div id="frame">
                            <?php $i = 1; ?>
                            <?php foreach ($this->getCollection() as $post): ?>
                                <div id="slider-<?php echo $i; ?>" class="product-block">
                                    <a href="<?php echo $post->getReadMoreUrl(); ?>">
                                        <img src="<?php echo Mage::getBaseUrl('media') . 'blog_post_image' .'/' . Mage::helper('neotheme_blog')->reImageName($post->getImage()); ?>" class="product-image">
                                    </a>
                                    <br><br>
                                    <h4><a href="<?php echo $post->getReadMoreUrl(); ?>"><?php echo $post->getTitle(); ?></a></h4>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>