<?php
$collection = $this->getHotNews();
?>

<div class="block-footer block-footer-2">
    <div class="block-footer-title"><strong><?php echo $this->__('Tin tức nổi bật'); ?></strong></div>
    <div class="block-footer-content">
        <?php foreach ($collection->getData() as $post): ?>
            <h2><span><?php echo date('d M Y', strtotime($post['created_at'])); ?></span></h2>
            <p class="new-content">
                <a href="<?php echo Mage::getBaseUrl() . "blog/tin-tuc/" . $post['cms_identifier']; ?>"><?php echo $post['title']; ?></a>
            </p>
        <?php endforeach; ?>
    </div>
</div>
